name: Build Web Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-web-extension:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/bootstrap-morfeo-action.yml

      - name: Bootstrap Web Extension
        run: yarn bootstrap:web-extension

      - name: Build Web Extension
        run: yarn build:devtool

