name: Build Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/bootstrap-morfeo-action

      - name: Bootstrap Docs
        run: yarn bootstrap:docs

      - name: Build Docs
        run: yarn build:docs

