name: Codecov

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install yarn
        run: npm install -g yarn

      - name: Bootstrap packages
        run: yarn reset
      
      - name: Run tests
        run: yarn test:ci

      - name: Codecov
        uses: codecov/codecov-action@v1.5.2

