name: Deploy Web Extension
on:
  release:
    types: [created]
jobs:
  deploy-web-extension:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/bootstrap-morfeo-action

      - name: Bootstrap Web Extension
        run: yarn bootstrap:web-extension
      
      - name: Deploy Web Extension
        run: yarn deploy:web-extension
        env:
          CHROME_WEB_CLIENT_ID: ${{ secrets.CHROME_WEB_CLIENT_ID }}
          WEB_EXTENSION_ID: ${{ secrets.WEB_EXTENSION_ID }}
          CHROME_WEB_REFRESH_TOKEN: ${{ secrets.CHROME_WEB_REFRESH_TOKEN }}
          CHROME_WEB_CLIENT_SECRET: ${{ secrets.CHROME_WEB_CLIENT_SECRET }}
