name: Publish packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/bootstrap-morfeo

      # TODO: Verify if this step is still needed
      - name: Assume unchanged for changed files
        run: s|
         for i in $(find -name package.json); do
           git update-index --assume-unchanged $i
         done
         git update-index --assume-unchanged lerna.json

      - name: Publish packages
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
