name: Publish packages
on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish-packages:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/bootstrap-morfeo

      - name: Publish packages
        run: yarn run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
